# Generated by Django 3.0.8 on 2020-07-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(verbose_name='Data Adaugare')),
                ('content', models.TextField(help_text='Continutul notitei', verbose_name='Text')),
                ('title', models.CharField(help_text='Titlu reprezentativ', max_length=120, verbose_name='Titlu')),
            ],
        ),
    ]
