# Generated by Django 3.0.8 on 2020-07-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='Este finalizata'),
        ),
        migrations.AlterField(
            model_name='note',
            name='add_date',
            field=models.DateTimeField(verbose_name='Data adaugare'),
        ),
    ]
