# Generated by Django 3.0.8 on 2020-07-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20200713_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='add_date',
            field=models.DateTimeField(verbose_name='Add Date'),
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='note',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name="It's Done"),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Title'),
        ),
    ]
